version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang

- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  assignees:
  - jonchang
