name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      unused:
        description: "Unused"
        required: false
  schedule:
    # Daily at 8 am
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
    - name: Authenticate with GitHub Container Registry
      run: |
        echo -n $GITHUB_TOKEN | docker login -u jonchang --password-stdin ghcr.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1.70.1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: RuboCop
      run: |
        bundle exec rubocop *.rb

    - uses: Swatinem/rust-cache@v1

    - run: make metadata

    - run: make extract

    - run: make site

    - name: Remove public full texts
      run: rm -rf _site/texts

    - name: Deploy to Neocities
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      id: neocities
      continue-on-error: true
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_KEY }}
        dist_dir: _site
        cleanup: true

    - name: Deploy to Neocities fallback
      if: ${{ steps.neocities.outcome == 'failure' && github.ref == 'refs/heads/master' }}
      uses: jonchang/deploy-neocities@master
      with:
        key: ${{ secrets.NEOCITIES_API_KEY }}
        dir: _site
        clean: true
