name: Download and update site archive

on:
  schedule:
    # Daily at 7 am
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: ruby/setup-ruby@v1.75.0
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Authenticate with GitHub Container Registry
        run: |
          echo -n $GITHUB_TOKEN | docker login -u jonchang --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: make extract

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libtext-csv-perl
          curl pi.dk/3/ | bash
          bundle install
          echo $PATH
          echo "/home/runner/bin" >> $GITHUB_PATH

      - run: make metadata

      - run: make download

      - run: make compress

      - run: docker build . --file Dockerfile --tag ghcr.io/jonchang/wanderinginn-archive:latest

      - name: Push the image
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        run: docker push ghcr.io/jonchang/wanderinginn-archive:latest
