name: Ping Internet Archive

on:
  schedule:
    # Daily at 6 am
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate with GitHub Container Registry
        run: |
          echo -n $GITHUB_TOKEN | docker login -u jonchang --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - run: make metadata

      - run: make extract

      - run: make download

      - run: ruby ping-wayback.rb
        env:
          INTERNET_ARCHIVE_COOKIE: ${{ secrets.INTERNET_ARCHIVE_COOKIE }}
